name: Package and Upload Helm Chart

on:
    push:
        branches:
            - master

jobs:
    package-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
            # - name: Build and Puch Docker Image
            #   uses: 
            
            - name: Install Helm
              uses: azure/setup-helm@v4
              with:
                 version: v3.13.1 # default is latest (stable)
              id: install

            - name: Package and Index Helm Repo
              uses: azure/CLI@v1
              with: 
                azcliversion: 2.30.0
                inlineScript: |
                    helm package getblobapp
                    helm repo index --url https://helmrepomalchiel.blob.core.windows.net/helm-repo-container/ .

            - name: Upload to blob storage
              uses: azure/CLI@v1
              with:
                  inlineScript: |
                      az storage blob upload-batch --account-name ${{ env.STORAGE_ACCOUNT_NAME }} --auth-mode key -d '$web' -s .
                      
        # Azure logout
            - name: logout
              run: |
                      az logout
              if: always()